const map = document.getElementById("map");
const area = document.getElementById("area");
const pointswar = document.getElementById("pointswar");

var map_height = 938;
var map_width = 938;
var pmc_size = 6144;

function zoom() {
  if (map.classList.contains("zoom")) {
    map.classList.remove("zoom");
  } else {
    map.classList.add("zoom");
  }
  map_height = map.getBoundingClientRect().height;
  map_width = map.getBoundingClientRect().width;
  load(map_height, map_width);
}

function show(x) {
  for (var div of pointswar.children) {
    div.firstChild.classList.add("void");
  div.style.zIndex = 0;
  }
  document.getElementById(x).parentElement.firstChild.classList.remove("void");
  document.getElementById(x).parentElement.style.zIndex = 1;
}

function load(map_height, map_width) {
  pointswar.innerHTML = "";
  for (var ville in data) {
    if (isNaN(data[ville]["__2"]) || data[ville]["Caractéristique"] == "Détruite") {
      //
    } else {
      var div = document.createElement("div");
      var point = document.createElement("div");
      var name = document.createElement("p");
      name.innerHTML = data[ville]["__1"];
      name.classList.add("void");
      div.classList.add("point");
      point.title = data[ville]["__1"];
      point.id = ville
      div.style.left = (data[ville]["Overworld"] + pmc_size) / (pmc_size * 2 / map_width) + "px";
      div.style.top = (data[ville]["__2"] + pmc_size) / (pmc_size * 2 / map_height) + "px";

      point.onclick = async function() {
        show(this.id);
      }


      div.appendChild(name);
      div.appendChild(point);
      pointswar.appendChild(div);
    }
  }
}








const data = [{
    "": "",
    "__1": "Villes",
    "Overworld": "X",
    "__2": "Y",
    "Nether": "nX",
    "__3": "nY",
    "Adresse nether": "Sortie",
    "__4": "Point",
    "__5": "Direction",
    "Population": "Actuel",
    "__6": "Inactif",
    "__7": "Banni",
    "__8": "Parti",
    "__9": "Total",
    "Architecture": "Général",
    "__10": "Détail",
    "Batiments": "Monuments",
    "__11": "Shops",
    "__12": "Total",
    "Caractéristique": "Status",
    "__13": "Fondateur",
    "__14": "Maire",
    "__15": "Date",
    "__16": "Commentaire",
    "Liens": "Forum",
    "__17": "Discord",
    "__18": "Map",
    "__19": "Pos"
  },
  {
    "": "⯀",
    "__1": "Herbeplate",
    "Overworld": -400,
    "__2": 184,
    "Nether": -50,
    "__3": 23,
    "Adresse nether": "Sortie 1",
    "__4": "Ouest",
    "__5": "Droite",
    "Population": 98,
    "__6": 29,
    "__7": 5,
    "__8": 11,
    "__9": 143,
    "Architecture": "Contemporain",
    "__10": "//",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Active",
    "__13": "sirlinium",
    "__14": "sirlinium",
    "__15": 2016,
    "__16": "Ville idéalement située proche du Spawn",
    "Liens": "Liens",
    "__17": "//",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Kraven",
    "Overworld": -744,
    "__2": 3888,
    "Nether": -93,
    "__3": 486,
    "Adresse nether": "Sortie 6",
    "__4": "Sud",
    "__5": "Droite",
    "Population": 20,
    "__6": 5,
    "__7": 1,
    "__8": 7,
    "__9": 33,
    "Architecture": "Multiple",
    "__10": "Ancien",
    "Batiments": 2,
    "__11": 1,
    "__12": 168,
    "Caractéristique": "Active",
    "__13": "AdriLaRace",
    "__14": "AdriLaRace       Kizuno",
    "__15": 2018,
    "__16": "Composée de différents quartiers à thème",
    "Liens": "//",
    "__17": "Liens",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Quartier Ouest",
    "Overworld": -744,
    "__2": 224,
    "Nether": -93,
    "__3": 28,
    "Adresse nether": "Sortie 2",
    "__4": "Ouest",
    "__5": "Droite",
    "Population": 21,
    "__6": 10,
    "__7": 0,
    "__8": 1,
    "__9": 32,
    "Architecture": "Moderne",
    "__10": "//",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Active",
    "__13": "lonely_knight",
    "__14": "HydroLike",
    "__15": 2015,
    "__16": "L’une des plus anciennes villes du serveur",
    "Liens": "Liens",
    "__17": "//",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Shïdo's Haven",
    "Overworld": 1024,
    "__2": 2000,
    "Nether": 128,
    "__3": 250,
    "Adresse nether": "Sortie 4",
    "__4": "Sud",
    "__5": "Gauche",
    "Population": 13,
    "__6": 4,
    "__7": 3,
    "__8": 1,
    "__9": 21,
    "Architecture": "Moderne",
    "__10": "Biomiméthique",
    "Batiments": 1,
    "__11": 2,
    "__12": 16,
    "Caractéristique": "Active",
    "__13": "Dakuraito      TheArtist72",
    "__14": "Dakuraito    TheArtist72",
    "__15": 2018,
    "__16": "Ville Biomiméthique avec de la végétation",
    "Liens": "Liens",
    "__17": "Liens",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Airom",
    "Overworld": -24,
    "__2": 2920,
    "Nether": -3,
    "__3": 365,
    "Adresse nether": "Sortie 5/6",
    "__4": "Sud",
    "__5": "Aucune",
    "Population": 5,
    "__6": 5,
    "__7": 0,
    "__8": 2,
    "__9": 12,
    "Architecture": "Sous-sol",
    "__10": "Naine",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Active",
    "__13": "_Sayanel",
    "__14": "_Sayanel",
    "__15": 2018,
    "__16": "Capitale autoproclamée du RP",
    "Liens": "Liens",
    "__17": "Liens",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Atlantis",
    "Overworld": -4904,
    "__2": -2840,
    "Nether": -613,
    "__3": -355,
    "Adresse nether": "Sortie 7",
    "__4": "Ouest",
    "__5": "Droite",
    "Population": 4,
    "__6": 2,
    "__7": 1,
    "__8": 3,
    "__9": 10,
    "Architecture": "Marin",
    "__10": "En surface, Prismarine",
    "Batiments": 5,
    "__11": 0,
    "__12": 55,
    "Caractéristique": "Active",
    "__13": "HydroLike",
    "__14": "HydroLike",
    "__15": 2019,
    "__16": "..",
    "Liens": "//",
    "__17": "Liens",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Dundwenium",
    "Overworld": -1256,
    "__2": 2510,
    "Nether": -157,
    "__3": 314,
    "Adresse nether": "Sortie 5",
    "__4": "Sud",
    "__5": "Droite",
    "Population": 2,
    "__6": 5,
    "__7": 1,
    "__8": 1,
    "__9": 9,
    "Architecture": "Antique",
    "__10": "Ville portuaire",
    "Batiments": 8,
    "__11": 0,
    "__12": 141,
    "Caractéristique": "Active",
    "__13": "Daewyn",
    "__14": "Daewyn",
    "__15": 2018,
    "__16": "La démesure Romaine.",
    "Liens": "Liens",
    "__17": "Liens",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "ValnyFrost",
    "Overworld": 568,
    "__2": -2504,
    "Nether": 71,
    "__3": -313,
    "Adresse nether": "Sortie 5",
    "__4": "Nord",
    "__5": "Droite",
    "Population": 5,
    "__6": 2,
    "__7": 1,
    "__8": 0,
    "__9": 8,
    "Architecture": "Médiéval",
    "__10": "Nordique",
    "Batiments": 2,
    "__11": 0,
    "__12": 86,
    "Caractéristique": "Active",
    "__13": "Doviculus",
    "__14": "Doviculus",
    "__15": 2018,
    "__16": "Construit dans les plus hautes montagnes du Nord",
    "Liens": "Liens",
    "__17": "Liens",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Haut-Bois",
    "Overworld": 632,
    "__2": 8,
    "Nether": 79,
    "__3": 1,
    "Adresse nether": "Sorte 3",
    "__4": "Est",
    "__5": "Gauche",
    "Population": 1,
    "__6": 6,
    "__7": 0,
    "__8": 0,
    "__9": 7,
    "Architecture": "Médiéval",
    "__10": "//",
    "Batiments": 1,
    "__11": 0,
    "__12": 12,
    "Caractéristique": "Active",
    "__13": "Haiko",
    "__14": "Krake_",
    "__15": 2015,
    "__16": "..",
    "Liens": "Ancien",
    "__17": "//",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Phénoria",
    "Overworld": -2616,
    "__2": -4128,
    "Nether": -327,
    "__3": -516,
    "Adresse nether": "Sortie 6",
    "__4": "Nord",
    "__5": "Gauche",
    "Population": 6,
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 6,
    "Architecture": "Médiéval",
    "__10": "//",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Active",
    "__13": "Psitaphile",
    "__14": "Psitaphile",
    "__15": 2018,
    "__16": "Inpirée de l’architecture du 12è siècle",
    "Liens": "Liens",
    "__17": "//",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "St-Ivrognes-sur-mer",
    "Overworld": 4856,
    "__2": -2112,
    "Nether": 607,
    "__3": -264,
    "Adresse nether": "Sortie 6",
    "__4": "Est",
    "__5": "Gauche",
    "Population": 6,
    "__6": 0,
    "__7": 0,
    "__8": 0,
    "__9": 6,
    "Architecture": "Autre",
    "__10": "Matériaux riches",
    "Batiments": 0,
    "__11": 0,
    "__12": 6,
    "Caractéristique": "Active",
    "__13": "MaxiCactus",
    "__14": "MaxiCactus",
    "__15": 2017,
    "__16": "..",
    "Liens": "//",
    "__17": "Liens",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Torvea",
    "Overworld": -5904,
    "__2": 1184,
    "Nether": -738,
    "__3": 148,
    "Adresse nether": "Sortie 7",
    "__4": "Ouest",
    "__5": "Gauche",
    "Population": 5,
    "__6": 0,
    "__7": 0,
    "__8": 0,
    "__9": 5,
    "Architecture": "Médiéval",
    "__10": "Gaulois",
    "Batiments": 0,
    "__11": 1,
    "__12": 4,
    "Caractéristique": "Active",
    "__13": "__Daw",
    "__14": "__Daw",
    "__15": 2020,
    "__16": "Ville perdu au milieu de l'océan",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Cube city",
    "Overworld": -1000,
    "__2": 600,
    "Nether": -125,
    "__3": 75,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": 1,
    "__6": 0,
    "__7": 0,
    "__8": 1,
    "__9": 2,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Active",
    "__13": "thejulol342",
    "__14": "Thomson",
    "__15": 2015,
    "__16": "..",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "BlockCity",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "Sortie 6",
    "__4": "Ouest",
    "__5": "..",
    "Population": 1,
    "__6": 0,
    "__7": 0,
    "__8": 0,
    "__9": 1,
    "Architecture": "Médiéval",
    "__10": 1,
    "Batiments": 1,
    "__11": 7,
    "__12": 9,
    "Caractéristique": "Active",
    "__13": "BlockAstre",
    "__14": "BlockAstre",
    "__15": 2018,
    "__16": "Possède un colonie sur le continent (la ville est sur une île)",
    "Liens": "..",
    "__17": "Liens",
    "__18": "..",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Clotopia",
    "Overworld": 1408,
    "__2": -4864,
    "Nether": 176,
    "__3": -608,
    "Adresse nether": "Sortie 7",
    "__4": "Nord",
    "__5": "Droite",
    "Population": 1,
    "__6": 0,
    "__7": 0,
    "__8": 0,
    "__9": 1,
    "Architecture": "Libre",
    "__10": "Principalement du bois",
    "Batiments": 0,
    "__11": 1,
    "__12": 30,
    "Caractéristique": "Active",
    "__13": "Clochette95",
    "__14": "Clochette95",
    "__15": 2019,
    "__16": "Domaine , reserve animaliere et vegetal",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Fongis",
    "Overworld": 2607,
    "__2": -2300,
    "Nether": 326,
    "__3": -288,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": 1,
    "__6": 0,
    "__7": 0,
    "__8": 0,
    "__9": 1,
    "Architecture": "Autre",
    "__10": "Champignons",
    "Batiments": 0,
    "__11": 0,
    "__12": "..",
    "Caractéristique": "Active",
    "__13": "SirYumma",
    "__14": "SirYumma",
    "__15": "..",
    "__16": "Village Schtroumpf",
    "Liens": "..",
    "__17": "//",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Oldgear",
    "Overworld": -830,
    "__2": 480,
    "Nether": -104,
    "__3": 60,
    "Adresse nether": "Sortie 3",
    "__4": "Ouest",
    "__5": "Gauche",
    "Population": 1,
    "__6": 0,
    "__7": 0,
    "__8": 0,
    "__9": 1,
    "Architecture": "Steampunk",
    "__10": "Mini steampunk",
    "Batiments": 0,
    "__11": 0,
    "__12": 9,
    "Caractéristique": "Active",
    "__13": "Yomna",
    "__14": "Yomna",
    "__15": 2015,
    "__16": "En construction",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Chêne-Fauve",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "Sortie 4",
    "__4": "Nord",
    "__5": "Droite",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Active",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "//",
    "__17": "//",
    "__18": "..",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "ForestBurghs",
    "Overworld": -768,
    "__2": -704,
    "Nether": -96,
    "__3": -88,
    "Adresse nether": "Sortie 3",
    "__4": "Nord",
    "__5": "Gauche",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Active",
    "__13": "Tazyek",
    "__14": "Tazyek",
    "__15": "..",
    "__16": "..",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "FrèsFort",
    "Overworld": -3928,
    "__2": -2384,
    "Nether": -491,
    "__3": -298,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Active",
    "__13": "BenjiX360",
    "__14": "BenjiX360",
    "__15": "..",
    "__16": "..",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Guruba",
    "Overworld": 376,
    "__2": 3800,
    "Nether": 47,
    "__3": 475,
    "Adresse nether": "Sortie 6",
    "__4": "Sud",
    "__5": "Gauche",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Active",
    "__13": "sitronnier",
    "__14": "sitronnier",
    "__15": "..",
    "__16": "..",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Kerbran",
    "Overworld": -320,
    "__2": -600,
    "Nether": -40,
    "__3": -75,
    "Adresse nether": "Sortie 3",
    "__4": "Nord",
    "__5": "Gauche",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "Médiéval",
    "__10": "//",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Active",
    "__13": "Aymeric",
    "__14": "Aymeric",
    "__15": "..",
    "__16": "..",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Nadnèra",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "Sortie 6",
    "__4": "Ouest",
    "__5": "Droite",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "Médiéval",
    "__10": "//",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Active",
    "__13": "..",
    "__14": "..",
    "__15": 2017,
    "__16": "..",
    "Liens": "//",
    "__17": "//",
    "__18": "..",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Naory",
    "Overworld": -3624,
    "__2": 624,
    "Nether": -453,
    "__3": 78,
    "Adresse nether": "Sortie 6",
    "__4": "Ouest",
    "__5": "Gauche",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "Moderne",
    "__10": "//",
    "Batiments": "//",
    "__11": "//",
    "__12": "..",
    "Caractéristique": "Active",
    "__13": "Skispace          Nom1s_",
    "__14": "Skispace          Nom1s_",
    "__15": "..",
    "__16": "..",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "NewbieTown",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "//",
    "__4": "//",
    "__5": "//",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Active",
    "__13": "..",
    "__14": "spacenewbie",
    "__15": "..",
    "__16": "..",
    "Liens": "//",
    "__17": "//",
    "__18": "..",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Octopolis",
    "Overworld": -104,
    "__2": -2448,
    "Nether": -13,
    "__3": -306,
    "Adresse nether": "Sortie 5",
    "__4": "Nord",
    "__5": "Droite",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": 0,
    "__11": 0,
    "__12": 26,
    "Caractéristique": "Active",
    "__13": "OCLASTAX",
    "__14": "OCLASTAX",
    "__15": "..",
    "__16": "..",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Panem",
    "Overworld": "//",
    "__2": "//",
    "Nether": "//",
    "__3": "//",
    "Adresse nether": "Sortie 5",
    "__4": "Sud",
    "__5": "Droite",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Active",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "//",
    "__17": "Liens",
    "__18": "//",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "PetitBois",
    "Overworld": -2920,
    "__2": -1800,
    "Nether": -365,
    "__3": -225,
    "Adresse nether": "Sortie 5",
    "__4": "Ouest",
    "__5": "Droite",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "Médiéval",
    "__10": "//",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Active",
    "__13": "Djinger",
    "__14": "Djinger",
    "__15": "..",
    "__16": "..",
    "Liens": "//",
    "__17": "Liens",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Ruf-Khazid",
    "Overworld": 4856,
    "__2": -2528,
    "Nether": 607,
    "__3": -316,
    "Adresse nether": "Sortie 7",
    "__4": "Est",
    "__5": "Gauche",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "Sous-sol",
    "__10": "Naine",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Active",
    "__13": "greg414",
    "__14": "greg414",
    "__15": "..",
    "__16": "..",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 1
  },
  {
    "": "⯀",
    "__1": "Shiganshina",
    "Overworld": 8,
    "__2": -704,
    "Nether": 1,
    "__3": -88,
    "Adresse nether": "Sortie 3",
    "__4": "Nord",
    "__5": "Droite",
    "Population": 0,
    "__6": 22,
    "__7": "..",
    "__8": 0,
    "__9": 22,
    "Architecture": "Médiéval",
    "__10": "Fantasy",
    "Batiments": "..",
    "__11": "..",
    "__12": 22,
    "Caractéristique": "Inactive",
    "__13": "Siflame, Blaze, Falco, Magicraft, Iron4Craft",
    "__14": "//",
    "__15": 2017,
    "__16": "la Ville de l'Académie Impériale des Mages",
    "Liens": "Liens",
    "__17": "//",
    "__18": "Liens",
    "__19": 2
  },
  {
    "": "⯀",
    "__1": "Contrastia",
    "Overworld": 2186,
    "__2": -1944,
    "Nether": 273,
    "__3": -243,
    "Adresse nether": "Sortie 5",
    "__4": "Est",
    "__5": "Gauche",
    "Population": 0,
    "__6": 18,
    "__7": 0,
    "__8": 0,
    "__9": 18,
    "Architecture": "Multiple",
    "__10": "//",
    "Batiments": 0,
    "__11": 1,
    "__12": "..",
    "Caractéristique": "Inactive",
    "__13": "DarkZanark          Gilnea",
    "__14": "//",
    "__15": 2016,
    "__16": "Chaque quartier, un thème",
    "Liens": "Liens",
    "__17": "//",
    "__18": "Liens",
    "__19": 2
  },
  {
    "": "⯀",
    "__1": "Ecorcia",
    "Overworld": 1128,
    "__2": -1800,
    "Nether": 141,
    "__3": -225,
    "Adresse nether": "Sortie 4",
    "__4": "Nord",
    "__5": "Droite",
    "Population": 0,
    "__6": 13,
    "__7": 0,
    "__8": 0,
    "__9": 13,
    "Architecture": "Autre",
    "__10": "Boisé",
    "Batiments": 0,
    "__11": 0,
    "__12": 11,
    "Caractéristique": "Inactive",
    "__13": "Waninoko",
    "__14": "//",
    "__15": 2016,
    "__16": "..",
    "Liens": "Liens",
    "__17": "//",
    "__18": "Liens",
    "__19": 2
  },
  {
    "": "⯀",
    "__1": "Acedia",
    "Overworld": 1208,
    "__2": -624,
    "Nether": 151,
    "__3": -78,
    "Adresse nether": "Sortie 4",
    "__4": "Est",
    "__5": "Gauche",
    "Population": 0,
    "__6": 8,
    "__7": 0,
    "__8": 0,
    "__9": 8,
    "Architecture": "Médiéval",
    "__10": "//",
    "Batiments": 0,
    "__11": 0,
    "__12": 59,
    "Caractéristique": "Inactive",
    "__13": "CroustiMuffin",
    "__14": "//",
    "__15": 2015,
    "__16": "Ville lumière",
    "Liens": "Liens",
    "__17": "//",
    "__18": "Liens",
    "__19": 2
  },
  {
    "": "⯀",
    "__1": "Epervine",
    "Overworld": 4264,
    "__2": 2752,
    "Nether": 533,
    "__3": 344,
    "Adresse nether": "Sortie 6",
    "__4": "Sud/Est",
    "__5": "Gauche",
    "Population": 0,
    "__6": 7,
    "__7": 0,
    "__8": 0,
    "__9": 7,
    "Architecture": "Médiéval",
    "__10": "//",
    "Batiments": 0,
    "__11": 0,
    "__12": 10,
    "Caractéristique": "Inactive",
    "__13": "Nokio",
    "__14": "//",
    "__15": 2017,
    "__16": "Ville fleurie",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 2
  },
  {
    "": "⯀",
    "__1": "Bourg du Savoir",
    "Overworld": -1660,
    "__2": -1870,
    "Nether": -208,
    "__3": -234,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": 0,
    "__6": 1,
    "__7": 0,
    "__8": 0,
    "__9": 1,
    "Architecture": "Médiéval",
    "__10": "//",
    "Batiments": 0,
    "__11": 0,
    "__12": 4,
    "Caractéristique": "Inactive",
    "__13": "Tehnry",
    "__14": "//",
    "__15": 2015,
    "__16": "..",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 2
  },
  {
    "": "⯀",
    "__1": "Neleria",
    "Overworld": 250,
    "__2": 100,
    "Nether": 31,
    "__3": 13,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": 1,
    "__8": "..",
    "__9": 1,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Inactive",
    "__13": "LucRatiff",
    "__14": "..",
    "__15": 2019,
    "__16": "..",
    "Liens": "..",
    "__17": "..",
    "__18": "Liens",
    "__19": 2
  },
  {
    "": "⯀",
    "__1": "Aubéclat",
    "Overworld": 3250,
    "__2": -2415,
    "Nether": 406,
    "__3": -302,
    "Adresse nether": "//",
    "__4": "//",
    "__5": "//",
    "Population": 0,
    "__6": 0,
    "__7": 0,
    "__8": 0,
    "__9": 0,
    "Architecture": "Médiéval",
    "__10": "//",
    "Batiments": 1,
    "__11": 0,
    "__12": 13,
    "Caractéristique": "Inactive",
    "__13": "Haiko",
    "__14": "//",
    "__15": 2015,
    "__16": "..",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 2
  },
  {
    "": "⯀",
    "__1": "Heafen",
    "Overworld": -2127,
    "__2": 1669,
    "Nether": -266,
    "__3": 209,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": 0,
    "__6": 0,
    "__7": 0,
    "__8": 0,
    "__9": 0,
    "Architecture": "Médiéval",
    "__10": "Îles flottantes",
    "Batiments": 0,
    "__11": 0,
    "__12": 7,
    "Caractéristique": "Inactive",
    "__13": "Wafoux",
    "__14": "//",
    "__15": 2015,
    "__16": "La cité volante",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 2
  },
  {
    "": "⯀",
    "__1": "Médiévapolis",
    "Overworld": -1000,
    "__2": -856,
    "Nether": -125,
    "__3": -107,
    "Adresse nether": "Sortie 3",
    "__4": "Nord",
    "__5": "Gauche",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "Médiéval",
    "__10": "//",
    "Batiments": 0,
    "__11": 0,
    "__12": 23,
    "Caractéristique": "Inactive",
    "__13": "Gaugauth02      Hitachi_",
    "__14": "Conte_Paul",
    "__15": "..",
    "__16": "..",
    "Liens": "//",
    "__17": "Liens",
    "__18": "Liens",
    "__19": 2
  },
  {
    "": "⯀",
    "__1": "Valoria",
    "Overworld": -1483,
    "__2": -3111,
    "Nether": -185,
    "__3": -389,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": 0,
    "__6": 0,
    "__7": 0,
    "__8": 0,
    "__9": 0,
    "Architecture": "Médiéval",
    "__10": "//",
    "Batiments": 1,
    "__11": 0,
    "__12": 51,
    "Caractéristique": "Inactive",
    "__13": "florianpal",
    "__14": "//",
    "__15": 2015,
    "__16": "Avec archaos5, Florianpal , Ouaich91 et Favret01",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 2
  },
  {
    "": "⯀",
    "__1": "Cavifar",
    "Overworld": 512,
    "__2": 2176,
    "Nether": 64,
    "__3": 272,
    "Adresse nether": "Sortie 4",
    "__4": "Sud",
    "__5": "Gauche",
    "Population": 0,
    "__6": 10,
    "__7": 0,
    "__8": 0,
    "__9": 10,
    "Architecture": "Desert",
    "__10": "//",
    "Batiments": 0,
    "__11": 0,
    "__12": 22,
    "Caractéristique": "Abandonnée",
    "__13": "Pokehadri",
    "__14": "//",
    "__15": "..",
    "__16": "..",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 3
  },
  {
    "": "⯀",
    "__1": "Valeix",
    "Overworld": 2256,
    "__2": -2328,
    "Nether": 282,
    "__3": -291,
    "Adresse nether": "Sortie 5",
    "__4": "Sud/Est",
    "__5": "//",
    "Population": 0,
    "__6": 2,
    "__7": 0,
    "__8": 0,
    "__9": 2,
    "Architecture": "Médiéval",
    "__10": "//",
    "Batiments": 0,
    "__11": 0,
    "__12": 10,
    "Caractéristique": "Abandonnée",
    "__13": "baptistevaleix",
    "__14": "//",
    "__15": 2017,
    "__16": "..",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 3
  },
  {
    "": "⯀",
    "__1": "//",
    "Overworld": 254,
    "__2": 2767,
    "Nether": 32,
    "__3": 346,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "Médiéval",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Abandonnée",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "..",
    "__18": "Liens",
    "__19": 3
  },
  {
    "": "⯀",
    "__1": "Animal City",
    "Overworld": 4992,
    "__2": -4936,
    "Nether": 624,
    "__3": -617,
    "Adresse nether": "Sortie 7",
    "__4": "Nord",
    "__5": "Droite",
    "Population": 0,
    "__6": 0,
    "__7": 0,
    "__8": 0,
    "__9": 0,
    "Architecture": "Médiéval",
    "__10": "//",
    "Batiments": 0,
    "__11": 0,
    "__12": 4,
    "Caractéristique": "Abandonnée",
    "__13": "BenjiX360",
    "__14": "//",
    "__15": "..",
    "__16": "..",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 3
  },
  {
    "": "⯀",
    "__1": "New Brick Valley",
    "Overworld": -920,
    "__2": 80,
    "Nether": -115,
    "__3": 10,
    "Adresse nether": "Sortie 3",
    "__4": "Ouest",
    "__5": "Droite",
    "Population": 0,
    "__6": 0,
    "__7": 0,
    "__8": 19,
    "__9": 19,
    "Architecture": "Moderne",
    "__10": "Gratte-ciel",
    "Batiments": 0,
    "__11": 0,
    "__12": 0,
    "Caractéristique": "Détruite",
    "__13": "Supercube49",
    "__14": "Supercube49",
    "__15": 2016,
    "__16": "Ancien secteur nord du Quartier ouest devenu indépendant",
    "Liens": "Liens",
    "__17": "//",
    "__18": "Liens",
    "__19": 4
  },
  {
    "": "⯀",
    "__1": "Le Hameau",
    "Overworld": 300,
    "__2": -25,
    "Nether": 38,
    "__3": -3,
    "Adresse nether": "//",
    "__4": "//",
    "__5": "//",
    "Population": 0,
    "__6": 0,
    "__7": 0,
    "__8": 6,
    "__9": 6,
    "Architecture": "Médiéval",
    "__10": "//",
    "Batiments": 0,
    "__11": 0,
    "__12": 0,
    "Caractéristique": "Détruite",
    "__13": "Lonely_knight",
    "__14": "LucRatiff",
    "__15": 2015,
    "__16": "..",
    "Liens": "Liens",
    "__17": "//",
    "__18": "Liens",
    "__19": 4
  },
  {
    "": "⯀",
    "__1": "Xanthos",
    "Overworld": -1100,
    "__2": 2900,
    "Nether": -138,
    "__3": 363,
    "Adresse nether": "//",
    "__4": "//",
    "__5": "//",
    "Population": 0,
    "__6": 4,
    "__7": "//",
    "__8": "//",
    "__9": 4,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "//",
    "__11": "//",
    "__12": "//",
    "Caractéristique": "Détruite",
    "__13": "Dhemonaq",
    "__14": "//",
    "__15": 2015,
    "__16": "Détruite puis repris par l'inquisition",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 4
  },
  {
    "": "⯀",
    "__1": "Ninou_City",
    "Overworld": -1241,
    "__2": -678,
    "Nether": -155,
    "__3": -85,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": 1,
    "__8": "..",
    "__9": 1,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Détruite",
    "__13": "..",
    "__14": "..",
    "__15": 2016,
    "__16": "..",
    "Liens": "Liens",
    "__17": "//",
    "__18": "Liens",
    "__19": 4
  },
  {
    "": "⯀",
    "__1": "OMG_City",
    "Overworld": 40,
    "__2": -1820,
    "Nether": 5,
    "__3": -228,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": 1,
    "__8": "..",
    "__9": 1,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Détruite",
    "__13": "CommandantOMG",
    "__14": "..",
    "__15": 2015,
    "__16": "..",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 4
  },
  {
    "": "⯀",
    "__1": "Aries",
    "Overworld": -6,
    "__2": -934,
    "Nether": -1,
    "__3": -117,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Détruite",
    "__13": "..",
    "__14": "TheYr",
    "__15": 2015,
    "__16": "..",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 4
  },
  {
    "": "⯀",
    "__1": "Cactus City",
    "Overworld": -50,
    "__2": 1852,
    "Nether": -6,
    "__3": 232,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Détruite",
    "__13": "Maxicactus",
    "__14": "..",
    "__15": 2015,
    "__16": "..",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 4
  },
  {
    "": "⯀",
    "__1": "Cubopolis",
    "Overworld": -81,
    "__2": -1803,
    "Nether": -10,
    "__3": -225,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": 0,
    "__11": 0,
    "__12": 0,
    "Caractéristique": "Détruite",
    "__13": "alex795",
    "__14": "..",
    "__15": 2016,
    "__16": "..",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 4
  },
  {
    "": "⯀",
    "__1": "Hydra City",
    "Overworld": 1200,
    "__2": 1300,
    "Nether": 150,
    "__3": 163,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Détruite",
    "__13": "SGIA            Cruvix",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 4
  },
  {
    "": "⯀",
    "__1": "Imladricity",
    "Overworld": -1261,
    "__2": 303,
    "Nether": -158,
    "__3": 38,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "Autre",
    "__10": "Campagne",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "Détruite",
    "__13": "Lytinium34",
    "__14": "..",
    "__15": 2016,
    "__16": "..",
    "Liens": "Liens",
    "__17": "//",
    "__18": "Liens",
    "__19": 4
  },
  {
    "": "⯀",
    "__1": "KARAK IZUL",
    "Overworld": -336,
    "__2": 3357,
    "Nether": -42,
    "__3": 420,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "Médiéval",
    "__10": "Steampunk",
    "Batiments": 0,
    "__11": 0,
    "__12": 0,
    "Caractéristique": "Détruite",
    "__13": "jedfu",
    "__14": "//",
    "__15": 2015,
    "__16": "La citée naine du fer",
    "Liens": "Ancien",
    "__17": "//",
    "__18": "Liens",
    "__19": 4
  },
  {
    "": "⯀",
    "__1": "Liberopolis",
    "Overworld": 2400,
    "__2": 2400,
    "Nether": 300,
    "__3": 300,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "Médiéval",
    "__10": "//",
    "Batiments": 0,
    "__11": 0,
    "__12": 0,
    "Caractéristique": "Détruite",
    "__13": "jumper_d_enfer",
    "__14": "//",
    "__15": 2015,
    "__16": "Un système de vote pour choisir votre sénat",
    "Liens": "Ancien",
    "__17": "//",
    "__18": "Liens",
    "__19": 4
  },
  {
    "": "⯀",
    "__1": "New Horizon",
    "Overworld": 281,
    "__2": 310,
    "Nether": 35,
    "__3": 39,
    "Adresse nether": "//",
    "__4": "//",
    "__5": "//",
    "Population": 0,
    "__6": 0,
    "__7": 0,
    "__8": 0,
    "__9": 0,
    "Architecture": "Médiéval",
    "__10": "//",
    "Batiments": 0,
    "__11": 0,
    "__12": 0,
    "Caractéristique": "Détruite",
    "__13": "IYIine",
    "__14": "//",
    "__15": 2015,
    "__16": "Jolie petite ville assez près du spawn",
    "Liens": "//",
    "__17": "//",
    "__18": "Liens",
    "__19": 4
  },
  {
    "": "⯀",
    "__1": "WATERVILLE",
    "Overworld": -183,
    "__2": -92,
    "Nether": -23,
    "__3": -12,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": 10,
    "__7": "..",
    "__8": "..",
    "__9": 10,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "Nightwatch14",
    "__14": "..",
    "__15": 2015,
    "__16": "Se situe sur l'eau",
    "Liens": "..",
    "__17": "//",
    "__18": "Liens",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Dawnguard",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": 6,
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 6,
    "Architecture": "Médiéval",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "Sandr3as",
    "__14": "..",
    "__15": 2016,
    "__16": "..",
    "Liens": "Liens",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Foruxia",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": 3,
    "__7": "..",
    "__8": "..",
    "__9": 3,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "Shaidan",
    "__14": "..",
    "__15": 2016,
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Persépolis",
    "Overworld": "//",
    "__2": "//",
    "Nether": "//",
    "__3": "//",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": 3,
    "__7": "..",
    "__8": "..",
    "__9": 3,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "Darius_III",
    "__14": "..",
    "__15": 2015,
    "__16": "Première ville oriental antique du serveur",
    "Liens": "..",
    "__17": "//",
    "__18": "//",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Frasia",
    "Overworld": -3090,
    "__2": -2060,
    "Nether": -386,
    "__3": -258,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": 1,
    "__7": "..",
    "__8": "..",
    "__9": 1,
    "Architecture": "Médiéval",
    "__10": "Principalement de bois",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "Luludatra",
    "__14": "..",
    "__15": 2015,
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "Liens",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Alaxonium",
    "Overworld": 740,
    "__2": 2800,
    "Nether": 93,
    "__3": 350,
    "Adresse nether": "Sortie 5",
    "__4": "Sud",
    "__5": "Gauche",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "Hitachi_",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "..",
    "__18": "Liens",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Arcadia",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Ascentia",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Azur",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": 2015,
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Bourg-Clochet",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Braavos",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": 2015,
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Cote Ouest",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Cuba",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "lonely_knight",
    "__14": "..",
    "__15": 2016,
    "__16": "Un village de vacances dans le plus pur style caribéen",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Despacitown",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Edorias",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "OtherxDreams",
    "__14": "..",
    "__15": 2015,
    "__16": "Ville nature",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Elidas",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": 2016,
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Elidos",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Frostwood",
    "Overworld": -1776,
    "__2": -3248,
    "Nether": -222,
    "__3": -406,
    "Adresse nether": "Sortie 6",
    "__4": "Nord",
    "__5": "Gauche",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "Thendeers",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "Liens",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Hélios",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Hyperion",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Isla de Cuba",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Kubaia Wurdah Itah",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "La cité égyptienne",
    "Overworld": 2400,
    "__2": 1440,
    "Nether": 300,
    "__3": 180,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "Coco45",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "Liens",
    "__17": "//",
    "__18": "Liens",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Litchfield",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Los Angeles",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Minemios",
    "Overworld": 734,
    "__2": 424,
    "Nether": 92,
    "__3": 53,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "Médiéval",
    "__10": "//",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "Lycoon",
    "__14": "..",
    "__15": 2015,
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "Liens",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Natureland",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": 2016,
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Nicia",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "lonely_knight",
    "__14": "..",
    "__15": 2015,
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Nogrod",
    "Overworld": 2592,
    "__2": -2168,
    "Nether": 324,
    "__3": -271,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "Sous-sol",
    "__10": "Naine",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "SirYuuma",
    "__14": "..",
    "__15": 2016,
    "__16": "La Citée Naine des Terres Éloignées",
    "Liens": "..",
    "__17": "//",
    "__18": "Liens",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Poesia Sin Fin",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "MrPinneau",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Port Meirion",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Port Middle",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Poulpe City",
    "Overworld": 467,
    "__2": -1123,
    "Nether": 58,
    "__3": -140,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "Liens",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Quartier Nord",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": 2016,
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Sacriffiasse",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "Antique",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "liliangoi3347",
    "__14": "..",
    "__15": 2015,
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Sandstone City",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Solaria",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "BirchLog",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Terraria-City",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Terraria-City",
    "Overworld": 3026,
    "__2": -3104,
    "Nether": 378,
    "__3": -388,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "Liens",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Tranquility Island",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Vanilla",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Venisia",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "..",
    "__14": "..",
    "__15": "..",
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Village de Noël",
    "Overworld": -2000,
    "__2": -1500,
    "Nether": -250,
    "__3": -188,
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "Shaidan",
    "__14": "..",
    "__15": 2015,
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "Liens",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Ville du lac",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "DragonAlec",
    "__14": "..",
    "__15": 2016,
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  },
  {
    "": "⯀",
    "__1": "Winterfell",
    "Overworld": "..",
    "__2": "..",
    "Nether": "..",
    "__3": "..",
    "Adresse nether": "..",
    "__4": "..",
    "__5": "..",
    "Population": "..",
    "__6": "..",
    "__7": "..",
    "__8": "..",
    "__9": 0,
    "Architecture": "..",
    "__10": "..",
    "Batiments": "..",
    "__11": "..",
    "__12": "..",
    "Caractéristique": "..",
    "__13": "XStaRiderX",
    "__14": "..",
    "__15": 2015,
    "__16": "..",
    "Liens": "..",
    "__17": "//",
    "__18": "..",
    "__19": 6
  }
]
